### ISSUE TITLE
App beendet sich sofort nach dem Start

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [Gebatzens/GG-Vertretung#10]
Die App lässt sich starten. Dann sieht man die Ladeanimation, dass der Vertretungsplan geladen wird. Kurz danach stürzt die App ab. Vielleicht existiert ein Bug bei Aufrufen des Vertretungsplans.

ADB Logcat:

---

	I/ActivityManager(  545): Start proc de.gebatzens.ggvertretungsplan for activity de.gebatzens.ggvertretungsplan/.MainActivity: pid=11443 uid=10110 gids={50110, 3003, 1028, 1015}
	D/ActivityThread(11443): handleBindApplication:de.gebatzens.ggvertretungsplan
	D/ActivityThread(11443): setTargetHeapUtilization:0.75
	D/ActivityThread(11443): setTargetHeapMinFree:2097152
	W/ggvp    (11443): Get GG Plans j44f0rf0i2vmecljnnftregoq6
	I/art     (11443): GcCauseBackground partial concurrent mark sweep GC freed 1179(46KB) AllocSpace objects, 3(4MB) LOS objects, 14% free, 10MB/12MB, paused 6.172ms total 18.757ms
	I/height of listItem:(11443): 288
	W/ggvp    (11443): onReceive de.gebatzens.ACTION_ALARM
	D/libEGL  (11443): loaded /system/lib/egl/libEGL_tegra.so
	E/        (11443): file /data/data/com.nvidia.NvCPLSvc/files/driverlist.txt: not found!
	I/        (11443): Attempting to load EGL implementation /system/lib//egl/libEGL_tegra_impl
	I/        (11443): Loaded EGL implementation /system/lib//egl/libEGL_tegra_impl
	D/libEGL  (11443): loaded /system/lib/egl/libGLESv1_CM_tegra.so
	D/libEGL  (11443): loaded /system/lib/egl/libGLESv2_tegra.so
	I/        (11443): Loading GLESv2 implementation /system/lib//egl/libGLESv2_tegra_impl
	D/OpenGLRenderer(11443): Enabling debug mode 0
	W/ProcessCpuTracker(  545): Skipping unknown process pid 11439
	W/ProcessCpuTracker(  545): Skipping unknown process pid 11442
	W/ProcessCpuTracker(  545): Skipping unknown process pid 11467
	I/art     (11443): GcCauseBackground partial concurrent mark sweep GC freed 2776(233KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 12MB/14MB, paused 12.438ms total 151.612ms
	I/ActivityManager(  545): Displayed de.gebatzens.ggvertretungsplan/.MainActivity: +1s260ms
	I/Timeline(  545): Timeline: Activity_windows_visible id: ActivityRecord{65c95f40 u0 de.gebatzens.ggvertretungsplan/.MainActivity t60} time:69975757
	I/Timeline(11443): Timeline: Activity_idle id: android.os.BinderProxy@64cc6dd8 time:69975785
	W/ggvp    (11443): Speichere ggvptoday
	W/ggvp    (11443): Speichere ggvptomorrow
	W/ggvp    (11443): Get GG Plans j44f0rf0i2vmecljnnftregoq6
	D/AndroidRuntime(11443): Shutting down VM
	E/AndroidRuntime(11443): FATAL EXCEPTION: main
	E/AndroidRuntime(11443): Process: de.gebatzens.ggvertretungsplan, PID: 11443
	E/AndroidRuntime(11443): java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
	E/AndroidRuntime(11443): 	at android.support.v7.widget.CardViewEclairMr1.getShadowBackground(CardViewEclairMr1.java:159)
	E/AndroidRuntime(11443): 	at android.support.v7.widget.CardViewEclairMr1.getMinWidth(CardViewEclairMr1.java:150)
	E/AndroidRuntime(11443): 	at android.support.v7.widget.CardView.onMeasure(CardView.java:181)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at android.widget.ScrollView.onMeasure(ScrollView.java:326)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1456)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:559)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	E/AndroidRuntime(11443): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:870)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:851)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	E/AndroidRuntime(11443): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	E/AndroidRuntime(11443): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	E/AndroidRuntime(11443): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2552)
	E/AndroidRuntime(11443): 	at android.view.View.measure(View.java:16521)
	E/AndroidRuntime(11443): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1915)
	E/AndroidRuntime(11443): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
	E/AndroidRuntime(11443): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
	E/AndroidRuntime(11443): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
	E/AndroidRuntime(11443): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
	E/AndroidRuntime(11443): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	E/AndroidRuntime(11443): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	E/AndroidRuntime(11443): 	at android.view.Choreographer.doFrame
	W/ActivityManager(  545):   Force finishing activity de.gebatzens.ggvertretungsplan/.MainActivity
	W/SurfaceFlinger(  153): captureScreen: fence wait timed out
	W/ggvp    (11443): Speichere ggvptoday
	W/ActivityManager(  545): Activity pause timeout for ActivityRecord{65c95f40 u0 de.gebatzens.ggvertretungsplan/.MainActivity t60 f}
	W/ggvp    (11443): Speichere ggvptomorrow
	I/Timeline(  895): Timeline: Activity_idle id: android.os.BinderProxy@64cc75b0 time:69976755
	D/ggvp    (11443): Up to date!
	I/Timeline(  545): Timeline: Activity_windows_visible id: ActivityRecord{654fca68 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:69976978
	I/Process (11443): Sending signal. PID: 11443 SIG: 9
	I/WindowState(  545): WIN DEATH: Window{65987ee0 u0 de.gebatzens.ggvertretungsplan/de.gebatzens.ggvertretungsplan.MainActivity}
	I/ActivityManager(  545): Process de.gebatzens.ggvertretungsplan (pid 11443) has died.

---

![screenshot_2015-02-23-08-36-25](https://cloud.githubusercontent.com/assets/3900641/6324244/ae4b7e22-bb37-11e4-8ff1-daa165054142.png)
![screenshot_2015-02-23-08-36-05](https://cloud.githubusercontent.com/assets/3900641/6324246/b2b6ea6e-bb37-11e4-8b62-bbc2d1ff8e95.png)

**Comment by Gebatzens** [comment]
Lag wahrscheinlich an CardView.setBackgroundColor. Es sollte setCardBackgroundColor sein. Die neue APK ist in /downloads/InfoApp-0.8.6.apk.
