### ISSUE TITLE
Keine Internetverbindung

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [Gebatzens/GG-Vertretung#15]
Beim Vertretungsplan steht oft "Keine Internetverbindung", obwohl es eine intakte Internetverbindung gibt.

**Comment by Gebatzens** [comment]
Könnte in 0.9.7 auch gefixt sein.

**Comment by NIPE-SYSTEMS** [comment]
Es könnte sein. Ich konnte den Fehler bis jetzt nicht mehr reproduzieren. Es ist mir leider entfallen, wie ich den Fehler bekommen habe. Der Issue könnte also geschlossen werden.

**Comment by NIPE-SYSTEMS** [comment]
Eben gerade hatte ich den Fehler erneut. Hier ein Screenshot. Man erkennt deutlich, dass oben eine Internetverbindung aufgebaut ist (3G-Verbindung), die App jedoch "Keine Internetverbindung" anzeigt.

![screenshot_2015-03-04-11-51-10](https://cloud.githubusercontent.com/assets/3900641/6482365/6937a362-c265-11e4-8f1c-db4e56f82689.png)
