### ISSUE TITLE
Updatefunktion funktioniert nicht

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [Gebatzens/GG-Vertretung#16]
Es ist aktuell (von Version 0.9.3) nicht möglich die aktuelle Version zu installieren. Man bekommt eine Benachrichtigung, dass eine neue Version verfügbar ist, es wird jedoch nicht die neuste Version installiert. Unter anderem ist auch der ChangeLog bei dem Fenster leer, bei dem der Nutzer gefragt wird, ob er das Update ausführen möchte.

Android Version: 4.4.4

![screenshot_2015-02-28-08-42-08](https://cloud.githubusercontent.com/assets/3900641/6425730/95f1f14e-bf38-11e4-9eec-f38162504377.png)

**Comment by asterix11** [comment]
Fixed, was a server-side issue.
