### ISSUE TITLE
Umlautfehler

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [Gebatzens/GG-Vertretung#25]
Bilder sagen mehr als 1000 Worte...

![screenshot_2015-03-06-11-24-56](https://cloud.githubusercontent.com/assets/3900641/6525959/753c407a-c40c-11e4-892e-3756fa967d67.png)

Aus "Gewaltpräventation" wird "Gewaltpr?ventation" (untere, orangene Card). Hier liegt wahrscheinlich ein Fehler des Zeichensatzes vor. Umlaute werden nicht richtig dargestellt.

**Comment by Gebatzens** [comment]
Python, iso-8859 und utf-8 = nur Probleme
