### ISSUE TITLE
Bilder beim Mensaplan verzerrt

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [Gebatzens/GG-Vertretung#26]
Die Bilder des Mensaplans wirken verzerrt (breiter als normal). (Vor ein paar Tagen gab es ein noch besseres Foto, dass diesen Bug belegt hat. Es ist leider kein Screenshot davon vorhanden.)

![screenshot_2015-03-06-14-34-26](https://cloud.githubusercontent.com/assets/3900641/6526094/2372b074-c40e-11e4-8e40-09f391af32ad.png)

**Comment by Gebatzens** [comment]
Sollte in fb96401bf1993c8c94581b4eb56d2faa32894262 gefixt sein (ist noch nicht in 0.9.7).
